---
- hosts: all
  tasks:
    - name: 'Instalando PHP5'
      apt:
        name: php5
        state: latest
      become: yes
    - name: 'Instalando Apache2'
      apt:
        name: apache2
        state: latest
      become: yes
